### ISSUE TITLE
Deserialize with defaults

### ISSUE THREAD

**Issue by amytimed** [khonsulabs/pot#12]
hello! would it be possible to add a `deserialize_as_with_default` function to the library?

for example if i serialize this:
```rust
#[derive(Serialize, Deserialize]
struct SaveData {
    property: u32
}
```
then, later on, I add a new field:
```rust
#[derive(Serialize, Deserialize]
struct SaveData {
    property: u32,
    new_property: u64
}
```
if i deserialize like this:
```rust
let save_data = value
    .deserialize_as_with_default(SaveData {
    property: 0,
    new_property: 0
}).unwrap();
```
it wouldnt give `missing field new_property` error, but would instead pick the missing property from the default

it is useful for backwards compatibility, currently im achieving something similar by iterating through mappings

**Comment by ecton** [comment]
I don't think this is possible without a completely custom proc macro. The closest support that I'm aware of from serde is [`DeserializeSeed`](https://docs.rs/serde/latest/serde/de/trait.DeserializeSeed.html), but this is something each type must be able to implement itself rather than something a serialization library adds support for.

With serde, each serialization library is being driven by the serde Serialize/Deserialize derives. The serialization library isn't able to query anything about the types, so there is no way for a library like Pot to use serde to do partial updates or "patch-like" deserialization.

With all this said, serde has a lot of flexible options for dealing with situations like this: for example, [annotating a field with `#[serde(default)]`](https://serde.rs/field-attrs.html#default) allows you to avoid missing field errors. There are other attributes listed on that page that can help too. Another option is to deserialize into a more flexible structure that contains Options and other ways to represent the data as loosely as possible, and then convert and validate the data into the desired runtime data structures from that loosely deserialized representation.

Regardless, I don't think there's much that Pot or any specific serde library serialization library can really add here. These features really need to be added directly to serde, and then all libraries can take advantage of them for free.
